### ISSUE TITLE
Not precise coordinates for rooms while setting up xiaomi card.

### ISSUE THREAD

**Issue by HGRT846** [sca075/mqtt_vacuum_camera#129]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

1. It shows room with wrong coordinates when using "GENERATE ROOMS CONFIG":

Valetudo:
![image](https://github.com/sca075/valetudo_vacuum_camera/assets/55946883/e556b6cc-9aac-4308-88ec-703f45b11bf9)
![image](https://github.com/sca075/valetudo_vacuum_camera/assets/55946883/f1a76345-4170-49a0-92c1-d6e33ba14584)

Card:
![image](https://github.com/sca075/valetudo_vacuum_camera/assets/55946883/83407754-16c9-46eb-9e72-18df99e85fc7)

You can see different borders

2. All my rooms have an id larger than 16 (I didnt find a way to change them in valetudo), thus I can`t change colors.

### What version of an integration has described problem?

2024.04.5

### What vacuum model do you have problems with?

Roborock S5

### Please firmware installed on your Vacuum.

Valetudo 2024.02.0 

### What type of platform you use?

Intel NUC (or generic x86_64)

### What version of Home Assistant do you use?

2024.4.4

### What type of installation are you running?

Home Assistant OS

**Comment by sca075** [comment]
@HGRT846 So far I can see the rooms are properly display, if you select the segment clean for when the vacuum start the room change slightly colour (meaning the indication on the card might be slightly off but the vacuum know what to do). The important think is the coordinates, does the vacuum move correctly to the go_to coordinates (on rand256 I use a room coordinate generation as the vacuum do not provide it in the json), I know that the boxes for the Hypfer can be sometime offset. Is the image at the original size?

**Comment by sca075** [comment]
Will enhance the rooms coordinates calculation for the Hypfer vacuums in the next version planned for the second week of May, I'm sorry for the inconvenience but as temporally please consider to manually correct the segments data in the card (that by the way will be stored and not change afterwords).  Of course if you need help with that I will be happy to assist you.

**Comment by sca075** [comment]
Changed the title for better tracking the issue. Also as mentioned, please, have a look to the colours management as per link above. Please also note that as I'm almost done with the 2024.05.0 the improvement you kindly proposed will be implemented on the release 2024.05.1. I just finished to re-flash the Hypfer firmware and work on it as soon I completed some tests pre-release for the 2024.05.0. Thanks in advance for your kind understanding, hope you will enjoy the camera and at your disposal for any required help ;)

**Comment by HGRT846** [comment]
> @HGRT846 So far I can see the rooms are properly display, if you select the segment clean, when the vacuum start the room change slightly colour (meaning the indication on the card might be slightly off but the vacuum know where to go). The important think is the coordinates, does the vacuum move correctly to the go_to coordinates (on rand256 I use a room coordinate generation as the vacuum do not provide it in the json, I can use a similar approach also for the Hypfer vacuums, as it is more precise), the boxes (calculated rooms area) for the Hypfer can be sometime offset. Is the image at the original size? Additionally, the rooms colours of course can change on the map that generate the camera but not in the vacuum. What do you mean with can't change the room colours? Please check the [docs for knowing how to change the colours](https://github.com/sca075/valetudo_vacuum_camera/blob/main/docs/colours.md) of the rooms.

I tried to change the colors yesterday, but it didn`t work until I restarted HA today. I thought that options to configure colors were meant to IDs of the rooms (1 - 8, 9 - 16), and I have my IDs in valetudo from 17 to 22, so I thought it is a bug. 

Anyway, thanks, I manually redacted coordinates and now everything works properly.

**Comment by sca075** [comment]
> > @HGRT846 So far I can see the rooms are properly display, if you select the segment clean, when the vacuum start the room change slightly colour (meaning the indication on the card might be slightly off but the vacuum know where to go). The important think is the coordinates, does the vacuum move correctly to the go_to coordinates (on rand256 I use a room coordinate generation as the vacuum do not provide it in the json, I can use a similar approach also for the Hypfer vacuums, as it is more precise), the boxes (calculated rooms area) for the Hypfer can be sometime offset. Is the image at the original size? Additionally, the rooms colours of course can change on the map that generate the camera but not in the vacuum. What do you mean with can't change the room colours? Please check the [docs for knowing how to change the colours](https://github.com/sca075/valetudo_vacuum_camera/blob/main/docs/colours.md) of the rooms.
> 
> I tried to change the colors yesterday, but it didn`t work until I restarted HA today. I thought that options to configure colors were meant to IDs of the rooms (1 - 8, 9 - 16), and I have my IDs in valetudo from 17 to 22, so I thought it is a bug.
> 
> Anyway, thanks, I manually redacted coordinates and now everything works properly.

Well no the colours are not following the ids is the room number draw anyway you what? it will be a great Idea to implement a function that grab the rooms in use and show the ID number ;)

**Comment by sca075** [comment]
@HGRT846 I probably found the way to get the data more accurate for the rooms: 
```
2024-05-01 16:54:47.250 INFO (glossyhardtofindnarwhal_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] glossyhardtofindnarwhal: Overlapping Layers
2024-05-01 16:54:47.255 DEBUG (glossyhardtofindnarwhal_camera_0) [custom_components.valetudo_vacuum_camera.utils.drawable] [(2915, 2145, 3100, 2515)]
2024-05-01 16:54:47.289 DEBUG (glossyhardtofindnarwhal_camera_0) [custom_components.valetudo_vacuum_camera.utils.drawable] [(2385, 1760, 2970, 2805)]
2024-05-01 16:54:47.309 DEBUG (glossyhardtofindnarwhal_camera_0) [custom_components.valetudo_vacuum_camera.utils.drawable] [(2665, 2055, 2910, 2215)]
2024-05-01 16:54:47.442 DEBUG (glossyhardtofindnarwhal_camera_0) [custom_components.valetudo_vacuum_camera.utils.drawable] [(2400, 2215, 2800, 2800)]
2024-05-01 16:54:47.470 DEBUG (glossyhardtofindnarwhal_camera_0) [custom_components.valetudo_vacuum_camera.utils.drawable] [(2815, 2500, 2925, 2740)]
2024-05-01 16:54:47.492 DEBUG (glossyhardtofindnarwhal_camera_0) [custom_components.valetudo_vacuum_camera.utils.drawable] [(2800, 2165, 2890, 2355)]
2024-05-01 16:54:47.676 DEBUG (glossyhardtofindnarwhal_camera_0) [custom_components.valetudo_vacuum_camera.utils.drawable] [(2395, 1765, 2700, 2200)] 
```
As soon I'm done with it I look in the possibility to change the rooms colours menus with the rooms ID. 
Will move this to the discussions and follow up as soon ;)
