### ISSUE TITLE
Only one room available when configuring room colors (reopened)

### ISSUE THREAD

**Issue by sca075** [sca075/mqtt_vacuum_camera#180]
### Discussed in https://github.com/sca075/valetudo_vacuum_camera/discussions/179

<div type='discussions-op-text'>

<sup>Originally posted by **kevinduong** May 29, 2024</sup>
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When changing room colors, only one option shows up for one room. The integration is reporting multiple segements (7). When adjusting this color, it didn't modify the floor color which I would have expected if there was an issue with segments/rooms. It correctly updated the color of the one room.  

![image](https://github.com/sca075/valetudo_vacuum_camera/assets/2790080/f0d94170-7157-42f4-bdf5-e9303bb13d93)

![image](https://github.com/sca075/valetudo_vacuum_camera/assets/2790080/c03c2cc4-3741-4c93-9e87-534d2be7c6de)

### What version of an integration has described problem?

2024.6.0

### What vacuum model do you have problems with?

Roborock S5 Valetudo

### Please firmware installed on your Vacuum.

2024.02.0

### What type of platform you use?

VEMLinux (Virtual Machine) such as Proxmox, VMWare, etc.

### What version of Home Assistant do you use?

core-2024.5.5

### What type of installation are you running?

Home Assistant OS

### Additional information

_No response_</div>

**Comment by sca075** [comment]
Although currently is implemented a work around for this issue, will investigate more in deep on it as per the room count for vacuums such as V1 should be 1 not 16 (that is the complete range of possible colours for the segments).
This issue therefore remain open for tracking purposes, and do not effect the component performances.

**Comment by sca075** [comment]
@kevinduong in the recent released I was probably able to fix this is issue. The Default number of room was reduce again to 1, the 2024.07.0 will be soon released and It would be really great when you confirm that you can still edit the rooms colours. If not I will try to close this within this milestone.

**Comment by sca075** [comment]
@kevinduong just to make it sure I will do the following test.
* Remove the camera completely from HA (including the files in .storage).
* Setup the entity again and check that all required files are available for counting the rooms.
This should ensure that the issue can be reproduced. So do not worry about the above request please.

**Comment by sca075** [comment]
Did re-test it and all works fine so will close this issue with next release.

**Comment by craggyh** [comment]
I am also experiencing this issue on the latest versions of HA/Valetudo/vacuum_camera as of 10/feb/2025. I only have one room available to colour even-though my vacuum attributes show 12 map segments available. Perhaps it's the mapping/numbering of the segments that's confusing the plugin.. 

![Image](https://github.com/user-attachments/assets/060fc4fb-f196-48a8-ba84-c8a2401517a5)

**Comment by craggyh** [comment]
Update: I just installed 2025.02.1 and I can now configure room colours again :-) Many thanks...

**Comment by sca075** [comment]
yep but recheck it and found that for V1 the config do not work well as per there is 0 returned instead of 1 a quick fix till the next version is: [ change this line
](https://github.com/sca075/mqtt_vacuum_camera/blob/9e425a880a3cfc48aec2391a40ddbaefb39829da/custom_components/mqtt_vacuum_camera/config_flow.py#L356) and put: + 1 
This allow the config to work.
