### ISSUE TITLE
The `schema` option is deprecated for MQTT vacuum

### ISSUE THREAD

**Issue by tomlut** [sca075/mqtt_vacuum_camera#214]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Receiving these warnings:

Logger: homeassistant.components.mqtt.vacuum
Source: components/mqtt/vacuum.py:173
integration: MQTT (documentation, issues)
First occurred: 19:13:50 (2 occurrences)
Last logged: 19:13:50

The `schema` option is deprecated for MQTT vacuum, but it was used in a discovery payload. Please contact the maintainer of the integration or service that supplies the config, and suggest to remove the option. Got {'object_id': 'valetudo_roborock_upstairs', 'schema': 'state', 'supported_features': ['battery', 'status', 'start', 'stop', 'pause', 'return_home', 'fan_speed', 'locate'], 'state_topic': 'valetudo/roborock_upstairs/hass/roborock_upstairs_vacuum/state', 'command_topic': 'valetudo/roborock_upstairs/hass/roborock_upstairs_vacuum/command', 'payload_start': 'START', 'payload_pause': 'PAUSE', 'payload_return_to_base': 'HOME', 'payload_stop': 'STOP', 'payload_locate': 'LOCATE', 'fan_speed_list': ['low', 'medium', 'high', 'max', 'off'], 'set_fan_speed_topic': 'valetudo/roborock_upstairs/FanSpeedControlCapability/preset/set', 'unique_id': 'roborock_upstairs_vacuum', 'availability_topic': 'valetudo/roborock_upstairs/$state', 'payload_available': 'ready', 'payload_not_available': 'lost', 'device': {'manufacturer': 'Roborock', 'model': 'S5', 'identifiers': ['roborock_upstairs'], 'sw_version': 'Valetudo 2024.02.0', 'configuration_url': 'http://valetudo-coarsedamagedbuffalo.local', 'name': 'robovac-upstairs'}, 'name': 'Robot', 'platform': 'mqtt'} at discovery topic homeassistant/vacuum/roborock_upstairs/roborock_upstairs_vacuum/config
The `schema` option is deprecated for MQTT vacuum, but it was used in a discovery payload. Please contact the maintainer of the integration or service that supplies the config, and suggest to remove the option. Got {'object_id': 'valetudo_roborock_downstairs', 'schema': 'state', 'supported_features': ['battery', 'status', 'start', 'stop', 'pause', 'return_home', 'fan_speed', 'locate'], 'state_topic': 'valetudo/roborock_downstairs/hass/roborock_downstairs_vacuum/state', 'command_topic': 'valetudo/roborock_downstairs/hass/roborock_downstairs_vacuum/command', 'payload_start': 'START', 'payload_pause': 'PAUSE', 'payload_return_to_base': 'HOME', 'payload_stop': 'STOP', 'payload_locate': 'LOCATE', 'fan_speed_list': ['low', 'medium', 'high', 'max', 'off'], 'set_fan_speed_topic': 'valetudo/roborock_downstairs/FanSpeedControlCapability/preset/set', 'unique_id': 'roborock_downstairs_vacuum', 'availability_topic': 'valetudo/roborock_downstairs/$state', 'payload_available': 'ready', 'payload_not_available': 'lost', 'device': {'manufacturer': 'Roborock', 'model': 'S5', 'identifiers': ['roborock_downstairs'], 'sw_version': 'Valetudo 2024.02.0', 'configuration_url': 'http://valetudo-improbablesorelark.local', 'name': 'robovac-downstairs'}, 'name': 'Robot', 'platform': 'mqtt'} at discovery topic homeassistant/vacuum/roborock_downstairs/roborock_downstairs_vacuum/config

### What version of an integration has described problem?

2024.07.34b2

### What vacuum model do you have problems with?

Roborock S5

### Please firmware installed on your Vacuum.

002008

### What type of platform you use?

Intel NUC (or generic x86_64)

### What version of Home Assistant do you use?

core-2024.7.3

### What type of installation are you running?

Home Assistant OS

### Function, that in your opinion is creating the issue.

None

**Comment by sca075** [comment]
@tomlut  This is ***components/mqtt/vacuum.py:173*** Home Assistant related, not from the camera. 
There is Valetudo firmware update to solve this issue => check the vacuums update page.

**Comment by tomlut** [comment]
Apologies. It was right there in front of me too:

> Logger: homeassistant.components.mqtt.vacuum

**Comment by sca075** [comment]
> Apologies. It was right there in front of me too:
> 
> > Logger: homeassistant.components.mqtt.vacuum

Absolutely no problem, we humans ;) thanks again for the help.

**Comment by tomlut** [comment]
Thanks for the tip about the firmware version. Updating now.
