### ISSUE TITLE
Requirements for mqtt_vacuum_camera not found: ['pillow==10.3.0']

### ISSUE THREAD

**Issue by TheZoker** [sca075/mqtt_vacuum_camera#224]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Since the HA beta 2024.08.0b1 I get this error in the logs:

```
Setup failed for custom integration 'mqtt_vacuum_camera': Requirements for mqtt_vacuum_camera not found: ['pillow==10.3.0'].

Unable to install package pillow==10.3.0: ERROR: Cannot install pillow==10.3.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### What version of an integration has described problem?

2024.07.4

### What vacuum model do you have problems with?

Roborock S5 Max

### What type of platform you use?

Intel NUC (or generic x86_64)

### What version of Home Assistant do you use?

core-2024.08.0b0

### What type of installation are you running?

Home Assistant OS

### Function, that in your opinion is creating the issue.

None

**Comment by TheZoker** [comment]
Issue is resolved by updating pillow to 10.4.0

**Comment by sca075** [comment]
Thanks I'm currently aboard but I will update the dependencies later apparently I need to check the beta release of HA.

**Comment by sca075** [comment]
@TheZoker on the next beta release will bump the pillow version on the manifest.json. I think the next beta is going out tomorrow as per today I'm quite busy with other thinks. But probably can do it also earlier.
Thanks once again for raising up this :)

**Comment by TheZoker** [comment]
I already updated the dependency in my local folder, so no hurry :)
