### ISSUE TITLE
Fails to start with HA 2024.8

### ISSUE THREAD

**Issue by Sn00kiT** [sca075/mqtt_vacuum_camera#235]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

After the update to Home Assistant Supervised 2024.8.0 the addon fails to start:

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 18:15:48 (1 occurrences)
Last logged: 18:15:48

Setup failed for custom integration 'mqtt_vacuum_camera': Requirements for mqtt_vacuum_camera not found: ['pillow==10.3.0'].

### What version of an integration has described problem?

2024.07.4

### What vacuum model do you have problems with?

Hyper/Valetudo

### Please firmware installed on your Vacuum.

2024.06.2

### What type of platform you use?

Intel NUC (or generic x86_64)

### What version of Home Assistant do you use?

core-2024.8.0

### What type of installation are you running?

Home Assistant OS

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode) text will be auto formatted to code.

```shell
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 18:15:48 (1 occurrences)
Last logged: 18:15:48

Setup failed for custom integration 'mqtt_vacuum_camera': Requirements for mqtt_vacuum_camera not found: ['pillow==10.3.0'].
```

### Function, that in your opinion is creating the issue.

None

**Comment by sca075** [comment]
@Sn00kiT update the camera to 2024.08.0 please the problem #234

**Comment by sca075** [comment]
I'm going to close this issue and I will pin it so that it will be visible also in the issue #234  discussion. #225  issue closed.

**Comment by Sn00kiT** [comment]
HA did not show me any updates available. i redownloaded it know from hacs and it works again flawlessly.
Thanks mate!!

**Comment by sca075** [comment]
@Sn00kiT Probably I will change the RN and put more in evidence ;) thanks anyhow for prompting reporting this at your disposal  ;)
