### ISSUE TITLE
Generating new entity with vacuum.my_robot = camera.my_camera

### ISSUE THREAD

**Issue by sca075** [sca075/mqtt_vacuum_camera#268]
### Discussed in https://github.com/sca075/mqtt_vacuum_camera/discussions/267

<div type='discussions-op-text'>

<sup>Originally posted by **scarylukas** November 11, 2024</sup>
Hello
I have two Xiaomi 1C devices with ValeTudo support.

Integration MQTT Vacuum's Camera in my case is only able to handle one camera correctly. When I try to add a second camera (another entity) I get the message "already_configured". Is it possible to handle two cameras from two different devices?</div>

**Comment by sca075** [comment]
Will need to somehow implement a new way to create the entry in order to add multiple vacuums (cameras) in home assistant. Currently we use the vacuumdevice.id + "_camera" will change it in order to get a more consistent way to add the new camera entries.

**Comment by markus-seidl** [comment]
"not planned" is sad, as I can't use this extension then :/
