### ISSUE TITLE
"already_configured" when adding second camera

### ISSUE THREAD

**Issue by markus-seidl** [sca075/mqtt_vacuum_camera#300]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When adding a second camera I get the error message "already_configured".
My robots are all named differently in home assistant and also have a different topic configured in valetudo:

![image](https://github.com/user-attachments/assets/135e6497-dc35-40c8-afe4-864fca9ec292)

![image](https://github.com/user-attachments/assets/1345f69a-04c8-4c4b-8cf6-ce21c2d73c93)

![image](https://github.com/user-attachments/assets/516cccec-2bf7-45c9-b9f0-873693503163)

![image](https://github.com/user-attachments/assets/9da9b33e-f637-452e-88e6-035e0b1d4b0c)

### What version of an integration has described problem?

2024.12.1

### What vacuum model do you have problems with?

Valetudo

### What type of platform you use?

Intel NUC (or generic x86_64)

### What version of Home Assistant do you use?

2024.12.1

### What type of installation are you running?

Home Assistant Core

### Function, that in your opinion is creating the issue.

None

**Comment by sca075** [comment]
Thanks for the report will be fixing this with the next release this week

**Comment by sca075** [comment]
Moment.. 
@markus-seidl the topic prefix is using "/" can you please use "_" instead? 
If not I got to add this scenario to the config_flow. 

The reason I guess is that the first camera had cleaning_camera as unique_id.

**Comment by markus-seidl** [comment]
I have all my MQTT sorted by floors, so using a _ would be meh.
The first camera created looks like this, which looks correctly named to me.

![image](https://github.com/user-attachments/assets/ab1fe51b-5929-4d42-9560-29cac2a226b3)

**Comment by sca075** [comment]
@markus-seidl I will be working on it, I need to make sure that the other users are not impacted by such changes.

I got your point and actually is a really good one.. so give me some hours (as soon I'm back home) and I will let you know how we solve it, okay?

**Comment by markus-seidl** [comment]
Thank you!
I did not want to introduce any pressure, solve it when you have time!

**Comment by sca075** [comment]
@markus-seidl for me is important to get it work for everyone and this honestly (as you also proposed) looks easy to fix, as I wrote earlier I just need to confirm what is best way to do it and that in the end all works better than before without affect the current usage.
Will push later today a beta 2024.12.2b1 also because currently there is another issue I'm working out and I would love to solve it within the next release.. if not with the 2024.12.2.
