### ISSUE TITLE
Pillow dependency is missing

### ISSUE THREAD

**Issue by Dinth** [sca075/mqtt_vacuum_camera#308]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

The intergration was not starting for me for the last couple of months. Only now i have managed to find time to look into that and i found the following error:

```
2024-12-28 07:30:38.132 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package pillow==10.3.0: × No solution found when resolving dependencies:
  ╰─▶ Because you require pillow==10.3.0 and pillow==11.0.0, we can conclude
      that your requirements are unsatisfiable.
2024-12-28 07:30:38.227 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'valetudo_vacuum_camera': Requirements for valetudo_vacuum_camera not found: ['pillow==10.3.0'].
```

Im not sure if it stopped due to HA/HASSOS update, or the integration update, but it used to work before

### What version of an integration has described problem?

2024.12.2

### What vacuum model do you have problems with?

Z10

### Please firmware installed on your Vacuum.

2024.11.0

### What type of platform you use?

VEMLinux (Virtual Machine) such as Proxmox, VMWare, etc.

### What version of Home Assistant do you use?

2024.12.5

### What type of installation are you running?

Home Assistant OS

### Function, that in your opinion is creating the issue.

None

**Comment by sca075** [comment]
It is strange as in the manifest it's pillow>=10.3.0 and pillow<=11.0.0.. and I'm currently running home assistant OS and 2025.1.0bx and it works without errors.. the 2024.12.2 is although our last release.

**Comment by sca075** [comment]
@Dinth can you confirm please the manifest.json?

**Comment by sca075** [comment]
@Dinth I don't think this issue was faced from anyone else. 
I really don't know why your system didn't update the integration correctly please check and eventually re-open this.

**Comment by Dinth** [comment]
Hey. I think it was some kind of HACS mess up because somehow i had both MQTT Vacuum Camera and Valetudo Vacuum Camera installed. After removing the Valetudo one, it seems that MQTT Vacuum Camera has started showing up in Add integration dialog.

**Comment by sca075** [comment]
> Hey. I think it was some kind of HACS mess up because somehow i had both MQTT Vacuum Camera and Valetudo Vacuum Camera installed. After removing the Valetudo one, it seems that MQTT Vacuum Camera has started showing up in Add integration dialog. 

Aaaaa this makes sense.. so if you remove the old one now all should work fine. 

Probably you missed the update that made the transition between the Valetudo and MQTT vacuum camera. This was several months ago.

**Comment by sca075** [comment]
@Dinth if you want the migration version you might download 2024.06.04. But to be sure I would advise that you remove the MQTT one and probably restore a backup before you removed the Valetudo one.

Else you might lose all settings and re-configure all from scratch.

I'm not sure if the docs are still having this part.
